pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'AkExpenses.Api, AkExpenses.Models'
    feedsToUse: 'select'
    vstsFeed: 'cd11d6d0-f336-4066-8b53-63b324f51660'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'AkExpenses.Api, AkExpenses.Models'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()